[tools]
cue = "0.14.1"
dprint = "0.50.1"
rust = "1.89.0"

# Tasks

[tasks.cli]
description = "Run the Dotfilet CLI"
quiet = true
run = "cargo run --quiet --bin dotfilet --"

[tasks.fix-style]
description = "Auto-format files to address style/lint issues"
run = "dprint fmt"

[tasks.test-style]
description = "Check whether files adhere to style/lint rules"
run = "dprint check"

[tasks.example-config]
description = "Emit the compiled configuration of an example"
usage = '''
arg "<example>" "The name of the example directory under ./examples/"
complete "example" run="ls ./examples"
'''
run = "cue export examples/{{arg(name='example')}}{/**,}/*.cue -t host=personal-laptop"
